var QUESTIONS = [
    { id: 0,  text: "Where did we first meet?", options: ["At school/university", "At work", "Through friends"] },
    { id: 1,  text: "Who texted first?", options: ["Girlfriend", "Boyfriend", "Both at the same time"] },
    { id: 2,  text: "Who said 'I love you' first?", options: ["Girlfriend", "Boyfriend", "We both did"] },
    { id: 3,  text: "Where was our first date?", options: ["A café", "The beach", "The movies"] },
    { id: 4,  text: "Who is more talkative?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 5,  text: "Who is shyer?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 6,  text: "What is my favorite food?", options: ["Pizza", "Rice & curry", "Pasta"] },
    { id: 7,  text: "What is my favorite drink?", options: ["Coffee", "Tea", "Juice"] },
    { id: 8,  text: "What is my favorite ice cream flavor?", options: ["Chocolate", "Vanilla", "Strawberry"] },
    { id: 9,  text: "Who sleeps more?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 10, text: "Who wakes up first?", options: ["Girlfriend", "Boyfriend", "Depending on the day"] },
    { id: 11, text: "Who snoozes the alarm more?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 12, text: "Who is usually late?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 13, text: "Who is more romantic?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 14, text: "Who apologizes first?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 15, text: "Who gets angry faster?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 16, text: "Who is more emotional?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 17, text: "Who is more dramatic?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 18, text: "Who laughs more?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 19, text: "Who cries during movies?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 20, text: "Who falls asleep during movies?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 21, text: "Who eats more?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 22, text: "Who always says 'I'm hungry'?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 23, text: "Who finishes the last piece of food?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 24, text: "Who cooks better?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 25, text: "Who uses the phone more?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 26, text: "Who replies to messages late?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 27, text: "Who sends more memes?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 28, text: "Who watches random reels and shows the other?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 29, text: "Who is better at planning surprises?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 30, text: "Who gives better gifts?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 31, text: "Who takes longer to get ready?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 32, text: "Who takes more selfies?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 33, text: "Who is more organized?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 34, text: "Who is messier?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 35, text: "Who spends more money?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 36, text: "Who fills the online cart but doesn't check out?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 37, text: "Who becomes quiet when it's time to pay the bill?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 38, text: "Who drives better?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 39, text: "Who gets lost even with Google Maps?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 40, text: "Who is more stubborn?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 41, text: "Who says sorry even when not wrong?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 42, text: "Who gives the best hugs?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 43, text: "Who is more protective?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 44, text: "Who is more jealous?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 45, text: "Who loves taking photos more?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 46, text: "Who insists on posting stories?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 47, text: "Who enjoys traveling more?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 48, text: "Who makes the other laugh the most?", options: ["Girlfriend", "Boyfriend", "Both"] },
    { id: 49, text: "Who loves the other more?", options: ["Girlfriend", "Boyfriend", "We love each other equally"] }
];
